### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by Big-Smarty** [Games-by-Mason/glslang-zig#1]
I tried using latest shader_compiler which uses this commit: https://github.com/Games-by-Mason/glslang-zig/commit/af4f26fcb2abb3e43f8794eb58df3289ab3b842b

(Latest commit of this repo also doesnt fix the issue; it only modifies the readme)

Unfortunately, the build.zig seems to use old build syntax (idk I started using zig a week ago):
tringle_zig on  main [!] via ↯ v0.14.0-dev.2424+7cd2c1ce8 via ❄️  impure (nix-shell-env) took 8s 
➜ zig build
/home/bigsmarty/.cache/zig/p/1220d8a973a82dc73994c611172c007155aa1938be78f672f003a30c7dca057e3fff/build.zig:864:9: error: expected type 'Build.Step.Compile.HeaderInstallation.Directory.Options', found 'build.install_headers_options__struct_117660'
        install_headers_options,
        ^~~~~~~~~~~~~~~~~~~~~~~
/home/bigsmarty/.cache/zig/p/1220d8a973a82dc73994c611172c007155aa1938be78f672f003a30c7dca057e3fff/build.zig:8:34: note: struct declared here
const install_headers_options = .{
                                ~^
/nix/store/fr22vi0kf59smmnqdf7dpgiq4pn9kjp7-zig-0.14.0-dev.2424+7cd2c1ce8/lib/std/Build/Step/Compile.zig:311:29: note: struct declared here
        pub const Options = struct {
                            ^~~~~~
/nix/store/fr22vi0kf59smmnqdf7dpgiq4pn9kjp7-zig-0.14.0-dev.2424+7cd2c1ce8/lib/std/Build/Step/Compile.zig:509:42: note: parameter type declared here
    options: HeaderInstallation.Directory.Options,
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
referenced by:
    build: /home/bigsmarty/.cache/zig/p/1220d8a973a82dc73994c611172c007155aa1938be78f672f003a30c7dca057e3fff/build.zig:597:28
    runBuild__anon_72751: /nix/store/fr22vi0kf59smmnqdf7dpgiq4pn9kjp7-zig-0.14.0-dev.2424+7cd2c1ce8/lib/std/Build.zig:2296:44
    22 reference(s) hidden; use '-freference-trace=24' to see all references

tringle_zig on  main [!] via ↯ v0.14.0-dev.2424+7cd2c1ce8 via ❄️  impure (nix-shell-env) took 2s 
➜ 

Or am I doing something wrong? Please help me out with this because I would really love to use shader_compiler

**Comment by Big-Smarty** [comment]
It does work on 0.13.0, I think I will just stay on that version for now

**Comment by MasonRemaley** [comment]
Hey! Welcome to Zig, and thanks for the report. :)

Looks like both glslang-zig and shader compiler were relying on a feature of Zig's type system that recently changed. I just pushed a commit to both repos fixing this, so you should be able to update to the latest Zig if you want to. I tested on `0.14.0-dev.2435+7575f2121`.

I think I'll tag a release on the next major Zig release so that it's easier for people to figure out which version of the library is compatible with their current Zig version.

Let me know if you run into any other issues or you have trouble with the upgrade!
